-- Tạo bảng Thủ Thư
CREATE TABLE ThuThu (
    MaTT NVARCHAR(50) PRIMARY KEY NOT NULL,
    MatKhau NVARCHAR(50) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL
);
-- Tạo bảng Thành Viên
CREATE TABLE ThanhVien (
    MaTV INTEGER PRIMARY KEY IDENTITY(1,1),
    HoTen NVARCHAR(100) NOT NULL,
    NamSinh NVARCHAR(10) NOT NULL
);

-- Tạo bảng Loại Sách
CREATE TABLE LoaiSach (
    MaLoai INTEGER PRIMARY KEY IDENTITY(1,1),
    TenLoai NVARCHAR(100) NOT NULL
);

-- Tạo bảng Sách
CREATE TABLE Sach (
    MaSach INTEGER PRIMARY KEY IDENTITY(1,1),
    TenSach NVARCHAR(100) NOT NULL,
    GiaThue INTEGER NOT NULL,
    MaLoai INTEGER NOT NULL,
    FOREIGN KEY (MaLoai) REFERENCES LoaiSach (MaLoai)
);

-- Tạo bảng Phiếu Mượn
CREATE TABLE PhieuMuon (
    MaPM INTEGER PRIMARY KEY IDENTITY(1,1),
    MaTT NVARCHAR(50) NOT NULL,
    MaTV INTEGER NOT NULL,
    MaSach INTEGER NOT NULL,
    Ngay DATE NOT NULL,
    TraSach INTEGER NOT NULL,
    TienThue INTEGER NOT NULL,
    FOREIGN KEY (MaTT) REFERENCES ThuThu (MaTT),
    FOREIGN KEY (MaTV) REFERENCES ThanhVien (MaTV),
    FOREIGN KEY (MaSach) REFERENCES Sach (MaSach)
);
